# Generated by Django 5.1.3 on 2024-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_2', '0002_author_book_page_book_price_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
