# Generated by Django 5.1.4 on 2024-12-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_session_key_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
